name: Go Lint
on: 
  pull_request:
    types:
      - opened
    branches:
      - main # only main
      - 'dev-*' # dev-new , dev-pages-about
      - 'feat/**' # feat/new , feat/pages/about
  workflow_dispatch:
  push:
    branches:
      - main # only main
      - 'dev-*' # dev-new , dev-pages-about
      - 'feat/**' # feat/new , feat/pages/about
    paths-ignore:
      - '.github/workflows/*'
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.11
      
      - name: Install Go-Lint
        run: | 
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.54.2
      
      - name: Run Go-Lint
        run: golangci-lint run --timeout=5m